### ISSUE TITLE
Separating download location, logs location and other files

### ISSUE THREAD

**Issue by Udinanon** [C0D3D3V/Moodle-DL#157]
## Avoid duplicates
* [x] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.
It' not  amjor problem, It's an enhancement that would immensely help me in my GUI project, as i would like to have the logs fixed near the main python code, the downloaded files in a user-defined location and the remaining files (cookies, moodle db, config, ...) in a different temporary folder

## Describe the solution you'd like
A simple change to the config helper to allow for separate store paths, and a fallback for backwards compatibility if only one folder is provided they all point to the same.

## Describe alternatives you've considered
I've considered, instead of calling the `run_main` function and passing arguments solely via config file, to instead access the internal functions of logging, MoodleService and DownloadService and feeding each the desired storage_path folders, but this would make for much less stable code as any internal references from one component to the other could break. This would also make the code much more fragile in case of any updates

## Additional context
I'm not using any of the email or xmpp services or any other components, so any decision made there is inconsequential to me.

**Comment by C0D3D3V** [comment]
The Idea when I created moodle-dl was the following, but I never had time to implement it:

My idea was that we use the default system configuration directory. 
The configuration directory can be determined with like this
```
    @staticmethod
    def get_user_config_directory():
        """Returns a platform-specific root directory for user config settings."""
        # On Windows, prefer %LOCALAPPDATA%, then %APPDATA%, since we can expect the
        # AppData directories to be ACLed to be visible only to the user and admin
        # users (https://stackoverflow.com/a/7617601/1179226). If neither is set,
        # return None instead of falling back to something that may be world-readable.
        if os.name == "nt":
            appdata = os.getenv("LOCALAPPDATA")
            if appdata:
                return appdata
            appdata = os.getenv("APPDATA")
            if appdata:
                return appdata
            return None
        # On non-windows, use XDG_CONFIG_HOME if set, else default to ~/.config.
        xdg_config_home = os.getenv("XDG_CONFIG_HOME")
        if xdg_config_home:
            return xdg_config_home
        return os.path.join(os.path.expanduser("~"), ".config")
```

And there we create a configuration directory `moodle-dl`. So on linux it would be `~/.config/moodle-dl/` and on windows `%Appdata%\moodle-dl\`.

Inside of that folder we could create subdirectories for every moodle instance that is configured. 

```
tree moodle-dl
moodle-dl
└── instances
    ├── Berlin
    │   ├── Cookies.txt
    │   ├── MoodleDownloader.log
    │   ├── config.json
    │   ├── moodle_state.db
    │   └── responses.log
    ├── Dortmund
    │   ├── Cookies.txt
    │   ├── MoodleDownloader.log
    │   ├── all_courses.json
    │   ├── config.json
    │   ├── moodle_state.db
    │   └── responses.log
    ├── RUB
    │   ├── Cookies.txt
    │   ├── MoodleDownloader.log
    │   ├── config.json
    │   ├── moodle_state.db
    │   └── responses.log
    └── global_config.json
```
 inside the  `global_config.json` we could store the names of the configured instances, alternatively we could just load all instances that are inside the `instances` folder. We could configure in the `global_config` where to store the downloaded files or inside the config per instance. I think it is easier to configure it in the global_config so all storage paths can be adjusted at once.
 
Extra Bonus enchantment: Also notification configurations could be moved to global (with option to overwrite it per instance, and de-/activate it per instance)). Actually all non specific configurations could be done globally, and made over-writeable locally. 
 
 
 
 This will take a lot of refactoring to implement, but if you like it an you have time you could implement it. 
 If not you could try to implement an workaround that works for you, you could for example just create an extra configuration only for your GUI, that links to the paths of the instance(s), so you can run your GUI from all directories without setting extra the sotrage path.

**Comment by C0D3D3V** [comment]
> A simple change to the config helper to allow for separate store paths, and a fallback for backwards compatibility if only one folder is provided they all point to the same.

You can also implement this solution. Sounds reasonable and needed for my ideal solution anyway.

**Comment by Udinanon** [comment]
Hmm, my project aims at being a much more straightforward and less advanced project, so a global config would actually go against my design.

I'll see how hard it is to make a fork with the extra config settings then and consider making a pull request in the future.

Do you have any other advice in how to implement this or where some hidden problems could arise? maybe some hard-to-spot dependency between services

**Comment by C0D3D3V** [comment]
I tried to design it as modular as possible, but it is actually not as modular as I wanted it (because I had not so much time). But what you want to do should be possible. Its basiclly just creating your own `run_main` function and leaving out stuff you do not need. 

If you do not want to change the `config_helper` yourself, I can also do the changes for you (but it will take some time..).

**Comment by C0D3D3V** [comment]
I guess with the refactoring I made this change should be easier. If you still want it, you could take a look.

**Comment by C0D3D3V** [comment]
So to simplify this back to your original request. What file paths do you want to be able to configure?

**Comment by C0D3D3V** [comment]
If I understand correct, you want to be able to set the path for the MoodleDL.log files and the download folder location inside of the config.json. The problem is, that the MoodleDL.log is created before the config is loaded. But setting the download location in the config should be possible.

**Comment by Udinanon** [comment]
Log locations could be also set via CLI, but that's lower priority for me
My biggest desire is to be able to set via config the download folder and perhaps cookies and db state and others to a separate folder.

**Comment by C0D3D3V** [comment]
so one path for download location and one for all misc files?

**Comment by C0D3D3V** [comment]
You can use now download_path  and misc_files_path in your config.json
If that is not enough feel free to open a new issue, or make a PR.  I also added the cli option --log-file-path

**Comment by Udinanon** [comment]
Fantastic, thank you for being so helpful!
