### ISSUE TITLE
Sharepoint file download support

### ISSUE THREAD

**Issue by juffis** [C0D3D3V/Moodle-DL#179]
## Avoid duplicates
* [ x ] This enhancement request has not already been raised before

## Is your feature request related to a problem? Please describe.

Studying at the uni currently and getting frustrated because half of the material is behind sharepoint urls.
Moodle downloader downloads aspx-files instead of the powerpoint and word documents.

## Describe the solution you'd like

If possible, enable download support for files in sharepoint, either in pdf-format or word / powerpoint /excel files.

## Describe alternatives you've considered

Manual labor takes away the idea behind moodle downloader.

**Comment by juffis** [comment]
Can I send you a private message or an email with the links? 

You raise a good point about the updated files. Slow way would be to download the document/powerpoint and check the hash, but that wouldn't be very practical.

**Comment by C0D3D3V** [comment]
Sure, you can find me in the discord channel that is linked in the readme (c0d3d3v). Or you send me an email, my address can be found on my profile. 

There would be ways to also trak changes on external sources like sharepoint. But I will not implement it in near feature. For example we could store a list of files that yt-dlp extracted, and make a diff, and then download only new files.

**Comment by C0D3D3V** [comment]
Implemented and released, please report if it does not work
