### ISSUE TITLE
Almost freezes with extreme RAM and CPU spikes on trying to download embedded images

### ISSUE THREAD

**Issue by AlexBocken** [C0D3D3V/Moodle-DL#181]
## Avoid duplicates
* [x] Bug is not already reported in another issue

## Describe the bug

When downloading linked files is enabled and an image is embedded into a page using `data:image/png;base64` moodle-dl seems to attempt to download this file. This results in huge RAM Spikes (in my case +7GB)  and CPU usage (100% usage) while also seemingly having to rescan all files? 
You can see a screenshot of such a culprit below:
![image](https://user-images.githubusercontent.com/32177905/221006581-066d1b4e-0623-435a-979e-2612e360c54c.png)
moodle-dl get's stuck on a page that looks like this. You can see that the image is embedded on the right.

## Steps to reproduce the issue

Requires HTML to have embedded images.

1. Enable downloading linked files
2. Attempt a download

Terminal Protocol: Kind of confused what a terminal protocol is. Running zsh in st if that helps. 

You can find a partial log file attached, I exited moodle after a while as it would take hours to finish.
[MoodleDownloader.log](https://github.com/C0D3D3V/Moodle-DL/files/10817344/MoodleDownloader.log)

The url is in the the form of `<moodle-url>/mod/page/view.php?id=<id>` if that helps

## Technical details

OS: Arch Linux  6.1.12
Moodle-DL Version: Most recent  `-git` AUR version: (`v2.2.2.4.r1.g9f65e57-1`)
Shell: zsh
Terminal: st (personal build)

## Expected behavior

Either 1. extract these images into a separate file or 2. skip them.

## Possible Fix

Simply skip these files? Otherwise an explicit check for embedded files and a subsequent extraction into a separate file could prove to be a quick fix maybe.

**Comment by C0D3D3V** [comment]
Can you send me the whole embeded image tag (via mail or discord) so I can test it with my local moodle?

**Comment by AlexBocken** [comment]
👌 Check your email inbox

**Comment by AlexBocken** [comment]
Had to delete my sql db but now everything works smoothly. Thanks for the quick work!
