### ISSUE TITLE
'staticmethod' object is not callable

### ISSUE THREAD

**Issue by j4wshua** [C0D3D3V/Moodle-DL#182]
## Describe the bug

moodle-dl crashes with the error message `'staticmethod' object is not callable`

## Steps to reproduce the issue
Run `moodle-dl`

 

Log with traceback: https://pastebin.com/MZv5p4Uh

## Technical details

OS: Debian 5.10.162-1 x86_64 GNU/Linux
Moodle-DL Version: 2.3.0.0

**Comment by C0D3D3V** [comment]
Thank you fro the report. 
Mh, maybe it is a problem with python version 3.9, I will try to reproduce it.

**Comment by C0D3D3V** [comment]
Oh I think I found the problem. Python 3.9 really does not allow @staticmethod on a global method. (it is also completely useless at that point, it was just a copy paste error, but python 3.10 seems to ignore it)

**Comment by C0D3D3V** [comment]
Please test the new release if it fixes the problem
