### ISSUE TITLE
Nothing downloads

### ISSUE THREAD

**Issue by tartho77** [C0D3D3V/Moodle-DL#196]
## Describe the bug 
 Hello, I have successfully installed moodle-dl.
I've done the configuration and selected the courses I want to download.
However, when I launch moodle-dl, all the courses and quizzes display "loaded" but I can't find any folders or pdf files to download.

What should I do?
Thanks in advance

## Include screenshots
[https://ibb.co/pjjxFL0](url)

## Arguments you used to run moodle-dl
--skip-cert-verify
--allow-insecure-ssl

## Include the terminal output:
[https://uploadnow.io/f/BzSbK1r](url)

## Technical details
 - OS: Windows 11
 - Moodle-DL Version [e.g. 22] : 2.3.2.0

**Comment by C0D3D3V** [comment]
Thanks for posting this bug. Interessting that you are the first that encounters this. Seems like I have made a mistake in the truncation of filenames. The filename that was given had no fileextension but one was expected. I will fix it tomorrow.


For your information the "loaded" statements in the log, they are all about meta data, so the information is loaded that is needed to download the files. But moodle-dl crashes after all metadata is downloaded.

**Comment by tartho77** [comment]
Thanks for the quick reply and the information.
Thanks also for the project.

**Comment by C0D3D3V** [comment]
I am very sorry that I did not keep my word ( "I will fix it tomorrow" ), the problem should now be solved. If not, please open a new issue.
