### ISSUE TITLE
config.json should be created unreadable to others

### ISSUE THREAD

**Issue by sijanec** [C0D3D3V/Moodle-DL#203]
## Description of the bug

`config.json` contains the private login token and is created with default permissions 0644. It should be created with permissions 0600, since it contains private data.

 

## Steps to reproduce the issue

Run `moodle-dl --init` and then `moodle-dl`. `config.json` is created in cwd with permissions `-rw-r--r--`.

## Expected behavior

`config.json` is created with permissions `-rw-------`.

## Possible Fix

```python
old = os.umask(0o770)
# create config file
os.umask(old)
```

## Technical details

- OS: `Linux c 6.1.66-gentoo-dist #1 SMP PREEMPT_DYNAMIC Mon Dec 11 00:22:21 CET 2023 x86_64 11th Gen Intel(R) Core(TM) i7-1165G7 @ 2.80GHz GenuineIntel GNU/Linux`
- `moodle-dl version: 2.3.2.0`

**Comment by C0D3D3V** [comment]
Thanks for the good idea. We can implement it. Interesting that 644 is default, wonder on what that depends. I guess you mean `umask(0o077)`

**Comment by sijanec** [comment]
Yeah, sorry, that's what I meant. It depends on the umask of the parent
process (shell), usually that's 022 as far as I know.

Regards

V V sob., 16. dec. 2023 ob 19:00 je oseba Daniel Vogt <
***@***.***> napisala:
