### ISSUE TITLE
Usage of -nt -u -pw just hangs moodle-dl

### ISSUE THREAD

**Issue by arman-ku** [C0D3D3V/Moodle-DL#205]
so when my login token expires, moodle-dl throws:
`The following error occurred during execution:
Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD" or "moodle-dl -nt -sso"
11:45:52 Exception: Your Moodle token has expired. To create a new one run "moodle-dl -nt -u USERNAME -pw PASSWORD" or "moodle-dl -nt -sso"`

When i run `moodle-dl -nt -u USERNAME -pw PASSWORD` with my credentials however, moodle-dl just hangs with no output until i keyboard interrupt.
Being curious i ran the command with the wrong credentials, and it does throw:
`Login Failed! (The Moodle System rejected the Request. Details: Ungültige Anmeldedaten. Versuchen Sie es noch einmal! (Error code: invalidlogin, Stacktrace: None, Debug info: None, Reproduction link: None)) Please try again.
Login Failed! (The Moodle System rejected the Request. Details: Ungültige Anmeldedaten. Versuchen Sie es noch einmal! (Error code: invalidlogin, Stacktrace: None, Debug info: None, Reproduction link: None)) Please try again.`

Interestingly, `moodle-dl --new-token` works just fine!

**Comment by C0D3D3V** [comment]
Ow, thank you, maybe one of my refactorings of the code introduced a bug. xD thats the bad thing about having no tests. I will test it, and see if thats the case.
