### ISSUE TITLE
Is there anyway to use it to DL all "Books" on a course?

### ISSUE THREAD

**Issue by memskez** [C0D3D3V/Moodle-DL#211]
Is there a way to use moodle-dl to download books for a course? eg: https://docs.moodle.org/403/en/Book_resource

I had hoped for Panopto also but see from a past request you could not gain access. Is not that painful as it produces a download list that you can use.

Thank you for your time :)

**Comment by C0D3D3V** [comment]
can you view books in the moodle mobile app?

**Comment by memskez** [comment]
Sure can. Downloading them now to see if I can access them straight from my phone storage.

**Comment by C0D3D3V** [comment]
If you can view them in moodle mobile app, than we can implement download of books also in moodle-dl

**Comment by C0D3D3V** [comment]
In what format would you like the books?
Simplest structure would be: 
"book title/chapter id/index.html"
would you also like a table of content?

would you like to have external links in a book downloaded?

Would you like to have the book in html format or markdown?

**Comment by C0D3D3V** [comment]
For Panopto open an own issue if you want it.

**Comment by memskez** [comment]
Legend, thank you! Works perfectly.

**Comment by C0D3D3V** [comment]
You now have to activate downloading of books explicitly use: `downoad_books`
