### ISSUE TITLE
Encountering this SSL error whilst running --init

### ISSUE THREAD

**Issue by Bigishchak04** [C0D3D3V/Moodle-DL#218]
## Description of Bug

I ran --init after successfully installing moodle-dl, and after I entered my username and password it gave me this SSL error - not really sure of how to get around it. I have tried using a VPN and using --skip-cert-verify , and using --allow-insecure-ssl

I am very confused as moodle-dl worked whilst I was on the university internet at the library

I looked at the other SSL error in issues but could not figure how to fix my issue using what was written here

## Steps to reproduce the issue

- ran --init after installation
- said no to all notification and error sentry
- entered my moodle URL
- entered my username and password

![CleanShot 2024-05-24 at 15 32 21@2x](https://github.com/C0D3D3V/Moodle-DL/assets/48356796/8808293f-e86a-4bb8-b5a8-429f8979bfc0)
![CleanShot 2024-05-24 at 15 35 02@2x](https://github.com/C0D3D3V/Moodle-DL/assets/48356796/3198ef27-8c72-497d-a18c-33df07e02520)
[MoodleDL.log](https://github.com/C0D3D3V/Moodle-DL/files/15436031/MoodleDL.log)
[config.json](https://github.com/C0D3D3V/Moodle-DL/files/15436024/config.json)

## Technical details

 - OS: MacOS 14.5
 - Moodle-DL Version [2.3.9]

**Comment by C0D3D3V** [comment]
"I am very confused as moodle-dl worked whilst I was on the university internet at the library"
They probably proxy external trafic through a balancer, that does the TLS negotiation for moodle... Thats why it could be that you get with external access the error, because you get the answer from the balancer instead of moodle.

**Comment by C0D3D3V** [comment]
Actually `--allow-insecure-ssl` should work. Whats the output if you add `--allow-insecure-ssl` to your `--init` command?

**Comment by C0D3D3V** [comment]
I just tested it with your moodle domain. `--allow-insecure-ssl` does work. I close this issue. If you still have problems, open a new one.
