### ISSUE TITLE
Need OAuth 2 authorization

### ISSUE THREAD

**Issue by MrMarvel** [C0D3D3V/Moodle-DL#225]
## Description of the problem
I want to grab materials from site `online-dpo.mirea.ru` but it uses only OAuth2 authorization.
![image](https://github.com/user-attachments/assets/980d7a5c-160b-48bd-a642-aa8ce005f32e)
P.S.
I tried `--sso` option but I couldn't retrieve info to put in console
## Solution 
Add a way to config auth through OAuth

**Comment by C0D3D3V** [comment]
Have you tried to login using `--sso` option?

**Comment by MrMarvel** [comment]
I tried sso option but I don't understand is that working properly
![image](https://github.com/user-attachments/assets/8152cfa5-a09a-4d06-ad56-74b89309d0ae)
![image](https://github.com/user-attachments/assets/3e6302ac-929c-4c9a-9059-3f93d66121e6)

**Comment by MrMarvel** [comment]
@C0D3D3V

**Comment by MrMarvel** [comment]
Is there way to use existing token like take from google developers tools to check cookies

**Comment by C0D3D3V** [comment]
As you can see in the screenshot of your browser, your moodle is currently under maintenance (Probably only the webservices API). Wait till you do no longer get this error. You should get a normal moodle page if it works, and an 303 redirect error with the token.

**Comment by C0D3D3V** [comment]
> Is there way to use existing token like take from google developers tools to check cookies

Some moodles allow viewing your access token on the moodle page.

You could also test if the moodle mobile app can connect to your moodle instance.
If so, this workflow could work: https://github.com/C0D3D3V/Moodle-DL/wiki/Copy-a-token-from-the-Moodle-app

But I guess you just have to wait, or ask your admin to turn of maintainance, so that you can log in again using moodle mobile app.

**Comment by MrMarvel** [comment]
> You could also test if the moodle mobile app can connect to your moodle instance.

Unfortunately, mobile app doesn't work. Moodle Desktop doesn't work too
![image](https://github.com/user-attachments/assets/a53d1e51-f3fe-410f-bcda-2f5471911820)


> or ask your admin to turn of maintainance, so that you can log in again using moodle mobile app

Maintaince message only on that url. Moodle site is working. I will try another day...

Can I use somehow this login data (oauth2code, sesskey)?
![image](https://github.com/user-attachments/assets/de887052-be40-4231-9e21-f9e9c84715e8)

**Comment by C0D3D3V** [comment]
I guess your moodle admin just added a redirect for the complete /admin/tool/ path. I guess he did not know that this is needed for moodle mobile to work. Or he disabled moodle mobile intentionally.
