### ISSUE TITLE
Config file not saved properly with _save method

### ISSUE THREAD

**Issue by MattiaOldani** [C0D3D3V/Moodle-DL#230]
## Description of the bug

When we modify a whitelist/blacklist during the execution of the `_select_courses_to_download` method in the `ConfigHazard` class we want to save the new config file, but there is a problem. When we call the `_save` method from the `ConfigHelper` class in `moodle-dl/config.py` file we use a workaround that call `os.fdopen` and `os.open` with `mode="w"`, but this is not working properly:
- if the new config file has a number of lines >= of the config file lines, there are no problems;
- if the new config file has a number of lines < of the old config file the workaround overwrites the lines that has index <= `len(config_formatted)` and keep the lines of the config file that has index > `len(config_formatted)`.

I think we have to reset the file and then write the new config file.

## Steps to reproduce the issue

We have a `config.json` file with some values under `download_course_ids` key.

### Starting point

![before](https://github.com/user-attachments/assets/6cf0172a-179e-478b-bfd9-47de7e54fda1)

### After moodle-dl --config

We execute `moodle-dl --config` and we remove two courses.

![after](https://github.com/user-attachments/assets/b5ceeb1a-156c-4ee0-9cfe-df535c8cb4a2)

The last two lines remain the same, and the third line from the bottom has been changed only in the first character.

## Expected behavior

I expect the file to be cleared before the writing of the new config file.

## Possible Fix

Clear the file before the writing of the new config file.

## Solution

I've alredy done a fork of the project and I've fixed this issue, you can see the source code [here](https://github.com/MattiaOldani/moodle-DL), if you assign me this issue I'm ready to merge the changes.

## Technical details

I'm running on Ubuntu22, I've installed `moodle-dl` with `sudo pip install moodle-dl`.

**Comment by C0D3D3V** [comment]
Really very very detailed bug report. ❤️
 I am always amazed at how long it takes for such bugs to be reported. Thank you. Your solution would have worked of course ;) but there is actually a flag for it, I just forgot to specify it back then when I reworked the save function.
