### ISSUE TITLE
'Nonetype' object has no attribute 'split' after moodle-dl tries to load lessons

### ISSUE THREAD

**Issue by Bigishchak04** [C0D3D3V/Moodle-DL#233]
## Description of the bug

When running Moodle-dl, it starts up as usual,  however, once it gets to download the lessons, it gives me the error the 'NoneType' object has no attribute 'split'

## Steps to reproduce the issue

run command moodle-dl "moodle-dl -ais"
downloads account information and proceeds as normal
starts loading course information 
starts loading lessons
the error occurs,  'NoneType' object has no attribute 'split' and the script stops 

![CleanShot 2024-11-05 at 11 24 40@2x](https://github.com/user-attachments/assets/0281e58c-823b-4b79-b259-9433f3f81a7a)

## Expected behaviour

After running "moodle-dl -ais" I expect it to download the new information and content uploaded to the Moodle site as usual 

## Technical details

 - OS: MacOS 15.01
 - Moodle-DL Version: 2.3.12

[MoodleDL.log](https://github.com/user-attachments/files/17631610/MoodleDL.log)

**Comment by C0D3D3V** [comment]
Thank you.
Funny, that error makes no sense at all. I will check it...

**Comment by C0D3D3V** [comment]
Try the new version 2.3.13. And tell me if it is fixed
